### ISSUE TITLE
Where to get transit data?

### ISSUE THREAD

**Issue by sid-kap** [policyclub/zoning-metadata#1]
If you want to expand this to all of CA, it seems like it would be a lot of work to get all the transit data for the entire state.

Are you considering any shortcuts for getting that data? For example, maybe asking the folks who made http://transitrichhousing.org if you could you their data?

**Comment by stevevance** [comment]
Use Transitland!

[Here are all the transit operators with known and public GTFS feeds in California](https://transit.land/feed-registry/?state=US-CA).

Here's how to get a list of them in JSON:
````
http://api.transit.land/api/v1/operators?state=US-CA
http://api.transit.land/api/v1/operators.geojson?state=US-CA
````

How to get a map of all stops (bounding box: southwest longitude, southwest latitude, northeast longitude, northeast latitude):
````
http://transit.land/api/v1/stops.geojson?bbox=-124.48,32.53,-114.13,42.01
````

Results are paginated. [Documentation](https://transit.land/documentation/datastore/api-endpoints.html).
- `?offset=50` is the index of the first entity to be displayed (starts with 0)
- By default, 50 entities are displayed per page. To change the number, specify `?per_page=1000`.
- To show the total number of results, use `?total=true`
