### ISSUE TITLE
Expand via International Open Data Day?

### ISSUE THREAD

**Issue by patwater** [policyclub/zoning-metadata#4]
Interested in working to expand this analysis as part of International Open Data Day 3/3? Could be a nice way to get other CfA brigades from around the state contributing. Would be good to polish up the contributing guidelines including how the 827 metadata fields are generated, iron out where to get transit data outside of SCAG region (guessing go to the local MPO / COG), find more zoning and land use data etc

**Comment by vykster** [comment]
@patwater we have a pretty tight focus for our work this month and next, we don't plan on doing anything for Open Data Day.

**Comment by patwater** [comment]
Roger that. Would one of you be interested in presenting a lightning talk at the LACI kickoff event on Friday? The lightning talk format is 5 minutes and 3 slides on a specific data product that #MapsCAsFuture which this is a perfect example of:

1. Why this data product matters for CA's climate goals
2. How that map was developed (peak under the hood)
3. Resulting product and any calls to action for collaboration

All the lightning talks will go back to back and then there will be an open house style forum for people to mingle and ask questions of the presenters.

**Comment by vykster** [comment]
What's the timing? We have some commitments already that day but if there's not a conflict we'll talk about it.

**Comment by patwater** [comment]
https://mapcasfuture.eventbrite.com

**Comment by vykster** [comment]
I'd be happy to do a lightening talk @patwater.
